name: Publish Snapshot Image

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build Boot Jar
      run: ./gradlew bootJar
    - name: Get the date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"
    - name: Clean the branch name
      id: branch_name
      run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
    - name: Truncate SHA
      id: sha
      run: echo "::set-output name=sha::$(echo ${GITHUB_SHA:0:7})"
    - name: Build Docker Image
      run: docker build -t navicore/sbjava-lotsofnames-server:${{ steps.branch_name.outputs.branch }}-${{ steps.date.outputs.date }}-${{ steps.sha.outputs.sha }} .
    - name: Login to Docker Hub
      uses: docker/login-action@v2 
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Push Docker Image to Docker Hub
      run: docker push navicore/sbjava-lotsofnames-server:${{ steps.branch_name.outputs.branch }}-${{ steps.date.outputs.date }}-${{ steps.sha.outputs.sha }}
