name: Release Docker Image

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: GitHub Tag Name 
      run: |
        echo "Tag name from github.ref_name: ${{  github.ref_name }}"
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build Boot Jar
      run: ./gradlew bootJar
    - name: Build Docker Image
      run: docker build -t navicore/sbjava-lotsofnames-server:${{  github.ref_name }} .
    - name: Login to Docker Hub
      uses: docker/login-action@v2 
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Push Docker Image to Docker Hub
      run: docker push navicore/sbjava-lotsofnames-server:${{  github.ref_name }}
